version: '3.9'

services:

  backend:
    container_name: "backend"
    build: app/backend/
    env_file: app/backend/.env
    networks:
      - network
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  network: {}
