version: '3.8'

services:

  backend:
    container_name: "backend"
    build: app/backend/
    networks:
      - server-side
      - client-side
    ports:
      - "8080:3000"
    env_file: app/backend/.env
    volumes:
      - ./app/backend/srcs:/backend
    depends_on:
      - database
    restart: always

  database:
    container_name: "database"
    image: postgres:15.1-alpine
    networks:
      - server-side
    volumes:
      - ./app/database/data:/var/lib/postgresql/data
    env_file: app/database/.env
    restart: always

  adminer:
    image: adminer
    networks:
      - server-side
    ports:
      - "8081:8080"
    restart: always

#  frontend:

networks:
  server-side: {}
  client-side: {}
