version: '3.9'

services:

  database:
    container_name: "database"
    image: postgres:15-alpine
    env_file: app/database/.env
    volumes:
      - type: bind
        source: "./app/database/data"
        target: "/var/lib/postgresql/data"
    networks:
      - network
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: "backend"
    build: app/backend/
    env_file: app/backend/.env
    depends_on:
      - database
    volumes:
      - type: bind
        source: "./app/backend/srcs"
        target: "/backend"
    networks:
      - network
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    container_name: "frontend"
    build: app/frontend/
    env_file: app/frontend/.env
    depends_on:
      - backend
    volumes:
      - type: bind
        source: "./app/frontend/srcs"
        target: "/frontend"
    networks:
      - network
    ports:
      - "4000:4000"
    restart: unless-stopped

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    env_file: app/pgadmin/.env
    networks:
      - network
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    container_name: "nginx"
    build: app/nginx/
    env_file: app/nginx/.env
    depends_on:
      - frontend
    networks:
      - network
    ports:
      - "443:443"
    restart: unless-stopped

networks:
  network: {}
