version: '3.9'

services:

  database:
    container_name: "database"
    image: postgres:15-alpine
    env_file: app/database/.env
    volumes:
      - ./app/database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network
    restart: unless-stopped

  backend:
    container_name: "backend"
    build: app/backend/
    env_file: app/backend/.env
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./app/backend/srcs:/backend
    networks:
      - network
    restart: unless-stopped

  frontend:
    container_name: "frontend"
    build: app/frontend/
    env_file: app/frontend/.env
    depends_on:
      - backend
    ports:
      - "4000:4000"
    volumes:
      - ./app/frontend/srcs:/frontend
    networks:
      - network
    restart: unless-stopped

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    env_file: app/pgadmin/.env
    ports:
      - "5000:5000"
    networks:
      - network
    restart: unless-stopped

networks:
  network: {}
